### ISSUE TITLE
square symbol

### ISSUE THREAD

**Issue by dacyh** [cappig/MC-status-bot#10]
the emoji that should be a green circle is not accessible, and most of the time it's just a square

**Comment by cappig** [comment]
The emoji depend on your device aka default system font. [This](https://emojipedia.org/large-green-circle/) is how the green circle emoji looks on different devices.

**Comment by dacyh** [comment]
I had already seen what the symbol should look like and found that my device does not show any emoji after version 11
[x](https://i.ibb.co/pPtY8dF/emoji.png)
