### ISSUE TITLE
Issues with the ping

### ISSUE THREAD

**Issue by cappig** [cappig/MC-status-bot#6]
The ping command sometimes doesn't return anything. Status channels display wrong status. (Reported by users)

**Comment by cappig** [comment]
The ping command has been fixed in be2acac748e2d05922944b4e88fd132c59a65d27. The ping library (`minecraft-server-util`) wasn't handling the request timing out. I wasn't able to reproduce the issue with the status channels locally.

**Comment by 404invalid-user** [comment]
fixed the auto pinger in commit 262d37c8e97a9882ecd5b25b4d8599083e520428 and the ping command will be fixed in a later update ~~totally didnt forget to fix that~~
